import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, HeadContent, Scripts, useRouter, } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/site-shell";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
function NotFoundComponent(){return <div className="flex min-h-screen flex-col items-center justify-center bg-burgundy px-5 text-center text-cream"><p className="font-script text-5xl text-rose">Lost your way?</p><h1 className="font-display text-8xl">404</h1><p className="mb-7 text-cream/70">That page has left the studio.</p><Button asChild className="rose-gradient rounded-full"><Link to="/">Return Home</Link></Button></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){const router=useRouter();useEffect(()=>reportLovableError(error,{boundary:"tanstack_root_error_component"}),[error]);return <div className="flex min-h-screen flex-col items-center justify-center bg-cream px-5 text-center"><h1 className="font-display text-5xl">This page didn't load</h1><p className="mt-3 text-muted-foreground">Please try again.</p><Button className="mt-6 rounded-full" onClick={()=>{router.invalidate();reset()}}>Try again</Button></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{name:"author",content:"SnS Glams Hair & Makeup Studio"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Allura&family=Cormorant+Garamond:wght@400;500;600&family=Jost:wght@400;500;600&display=swap"},{rel:"icon",href:"/favicon.png",type:"image/png"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><AppShell><Outlet/></AppShell></QueryClientProvider>}
