import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import useEmblaCarousel from "embla-carousel-react";
import { ArrowLeft, ArrowRight, Aperture, CalendarDays, Camera, Heart, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { BookButton, CTABanner, Reveal, SectionHeading, TextLink } from "@/components/editorial";
import { services, featuredPackages } from "@/data/services";
import { gallery } from "@/data/gallery";
import { posts } from "@/data/posts";
import { reviews } from "@/data/reviews";
import { BeautyMotion } from "@/components/beauty-motion";
import { homePortraits } from "@/data/gallery";

const trustItems = [
  { Icon: Heart, label: "Bridal Specialists" },
  { Icon: Sparkles, label: "Flawless Installs" },
  { Icon: Camera, label: "In-House Photo Studio" },
  { Icon: CalendarDays, label: "Open 7 Days" },
];
const valueItems = [
  { Icon: Sparkles, label: "Artistry" },
  { Icon: Heart, label: "Comfort" },
  { Icon: Aperture, label: "Every Occasion" },
];

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"SnS Glams | Luxury Hair, Makeup & Photo Studio in Maryland"},{name:"description",content:"Luxury makeup, hair installations, braiding and studio photography in Maryland."},{property:"og:title",content:"SnS Glams Hair & Makeup Studio"},{property:"og:description",content:"Glam, hair and beautiful portraits—all under one roof."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Home});
function Home(){return <><Hero/><Trust/><Marquee/><Services/><About/><BeautyMotion/><Packages/><Occasions/><Gallery/><Reviews/><Blog/><CTABanner/></>}
function Hero(){const [ref,api]=useEmblaCarousel({loop:true});const [index,setIndex]=useState(0);const select=useCallback(()=>setIndex(api?.selectedScrollSnap()||0),[api]);useEffect(()=>{if(!api)return;api.on("select",select);const timer=setInterval(()=>api.scrollNext(),6000);return()=>{clearInterval(timer);api.off("select",select)}},[api,select]);return <section className="relative h-[100svh] min-h-[690px] overflow-hidden bg-ink text-cream" ref={ref}><div className="flex h-full">{services.map((s,i)=><div key={s.id} className="relative min-w-0 flex-[0_0_100%]"><img src={s.image} alt={s.name} width={1200} height={1600} className={`absolute inset-0 h-full w-full object-cover object-top ${i===index?"kenburns":""}`} fetchPriority={i===0?"high":"auto"}/><div className="absolute inset-0 bg-gradient-to-r from-ink via-burgundy/70 to-transparent"/><div className="relative z-10 mx-auto flex h-full max-w-7xl items-center px-5 pt-24"><div className="max-w-2xl"><p className="mb-5 text-xs tracking-[.28em] text-rose">{s.eyebrow}</p><p className="font-script text-4xl text-rose sm:text-5xl">Made for your moment</p><h1 className="font-display text-5xl uppercase leading-[.88] sm:text-7xl lg:text-8xl">{s.headline}</h1><p className="mt-5 max-w-lg text-base text-cream/75 sm:text-lg">{s.description}</p><div className="mt-8 flex flex-wrap gap-3"><BookButton service={s.id} label={`Book ${s.name.replace("Studio ","")}`}/><Button asChild variant="outline" className="rounded-full border-cream/40 bg-transparent text-cream hover:bg-cream hover:text-burgundy"><Link to={s.href}>Explore <ArrowRight/></Link></Button></div></div></div></div>)}</div><div className="absolute bottom-8 left-5 right-5 z-20 mx-auto flex max-w-7xl items-end justify-between"><div className="flex gap-2">{services.map((_,i)=><button key={i} onClick={()=>api?.scrollTo(i)} className="w-12 text-left text-xs"><span>0{i+1}</span><span className={`mt-2 block h-px ${i===index?"bg-rose":"bg-cream/35"}`}/></button>)}</div><div className="flex gap-2"><Button size="icon" variant="outline" className="rounded-full border-cream/40 bg-transparent text-cream" onClick={()=>api?.scrollPrev()}><ArrowLeft/></Button><Button size="icon" variant="outline" className="rounded-full border-cream/40 bg-transparent text-cream" onClick={()=>api?.scrollNext()}><ArrowRight/></Button></div></div></section>}
function Trust(){return <section className="bg-ink px-5 py-7 text-cream"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-5 md:grid-cols-4">{trustItems.map(({Icon,label})=><div key={label} className="flex items-center justify-center gap-3 border-r border-rose/30 text-xs uppercase tracking-[.12em]"><Icon className="size-5 text-rose"/>{label}</div>)}</div></section>}
function Marquee(){const text="SOFT GLAM ✦ FULL GLAM ✦ BRIDAL ✦ 360 INSTALLS ✦ BRAIDS ✦ PHOTOSHOOTS ✦ ";return <div className="overflow-hidden border-y border-rose/30 bg-blush py-3 text-sm tracking-[.2em] text-burgundy"><div className="marquee-track flex w-max whitespace-nowrap"><span>{text.repeat(3)}</span><span>{text.repeat(3)}</span></div></div>}
function Services(){return <section className="px-5 py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="ALL UNDER ONE ROOF" script="Find your signature" title="Our Services"/><div className="grid grid-cols-2 gap-6 md:grid-cols-4">{services.map((s,i)=><Reveal key={s.id}><Link to={s.href} className="group block text-center"><div className="relative mx-auto aspect-square max-w-64 rounded-full border border-rose p-2 transition group-hover:rotate-2"><img src={homePortraits[i]} alt={s.name} loading="lazy" width={1200} height={1600} className="h-full w-full rounded-full object-cover transition duration-700 group-hover:scale-[1.03]"/></div><h3 className="mt-5 font-display text-2xl">{s.name}</h3><p className="text-xs uppercase tracking-[.14em] text-muted-foreground">{s.packages[0]?.price?`From $${s.packages[0].price}`:"Quote on request"}</p></Link></Reveal>)}</div></div></section>}
function About(){return <section className="bg-blush px-5 py-24"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-2 md:items-center"><Reveal className="grid grid-cols-2 gap-3"><img src={homePortraits[4]} alt="SnS Glams makeup client" loading="lazy" className="mt-12 aspect-[3/4] w-full object-cover"/><img src={homePortraits[5]} alt="SnS Glams hair client" loading="lazy" className="aspect-[3/4] w-full object-cover"/></Reveal><div><SectionHeading eyebrow="BEAUTY WITH INTENTION" script="Welcome to SnS Glams" title="Come as you are. Leave unforgettable."/><p className="max-w-xl text-muted-foreground">Makeup artistry, flawless hair and a fully equipped photo studio come together in one welcoming Maryland space.</p><div className="mt-8 grid gap-5 sm:grid-cols-3">{valueItems.map(({Icon,label})=><div key={label}><Icon className="mb-2 text-rose"/><h3 className="font-display text-xl">{label}</h3></div>)}</div><div className="mt-8"><TextLink to="/about">Our Story</TextLink></div></div></div></section>}
function Packages(){return <section className="bg-nude px-5 py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="SIGNATURE LOOKS" script="Curated for you" title="Our Favorites"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{featuredPackages.map((p,i)=>{const s=services.find(x=>x.id===p.service);if(!s)return null;return <Reveal key={p.name}><article className="group overflow-hidden border border-burgundy/25 bg-cream"><div className="aspect-[4/5] overflow-hidden"><img src={homePortraits[i+6]} alt={p.name} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-5"><p className="text-xs uppercase text-muted-foreground">{s.name}</p><h3 className="font-display text-2xl">{p.name}</h3><div className="mt-4 flex items-center justify-between"><span>${p.price}</span><BookButton service={p.service} packageName={p.name} label="Book" className="h-9 px-5"/></div></div></article></Reveal>})}</div></div></section>}
function Occasions(){const names=["Weddings","Birthdays","Anniversaries","Graduations","Photoshoots"];return <section className="bg-burgundy px-5 py-24 text-cream grain"><div className="relative z-10 mx-auto max-w-7xl"><SectionHeading eyebrow="EVERY MILESTONE" script="For every chapter" title="Your Occasion, Elevated" light/><div className="grid gap-3 md:grid-cols-5">{names.map((name,i)=>{const image=gallery[i%gallery.length];return image?<Reveal key={name}><div className="group relative aspect-[3/5] overflow-hidden"><img src={image.src} alt={name} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-ink to-transparent"/><h3 className="absolute bottom-5 left-5 font-display text-2xl">{name}</h3></div></Reveal>:null})}</div></div></section>}
function Gallery(){return <section className="px-5 py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="SELECTED WORK" script="From the studio" title="Featured Gallery"/><div className="grid auto-rows-[220px] grid-cols-2 gap-3 md:grid-cols-4">{gallery.slice(0,6).map((g,i)=><Reveal key={i} className={`${i===0||i===5?"row-span-2 col-span-2":""} overflow-hidden`}><img src={g.src} alt={g.alt} loading="lazy" className="h-full w-full object-cover transition duration-700 hover:scale-105"/></Reveal>)}</div><div className="mt-8 text-center"><TextLink to="/gallery">View Full Gallery</TextLink></div></div></section>}
function Reviews(){return <section className="bg-blush px-5 py-24"><div className="mx-auto grid max-w-7xl items-center gap-0 md:grid-cols-[1.2fr_.8fr]"><img src={homePortraits[10]} alt="SnS Glams beauty portrait" loading="lazy" className="h-[620px] w-full object-cover"/><Reveal className="relative z-10 bg-burgundy p-9 text-cream md:-ml-20">{reviews.length===0?<><p className="font-script text-4xl text-rose">What our babes say</p><h2 className="font-display text-5xl">Loved your glam?</h2><p className="mt-4 text-cream/70">We'd love to hear about it. Share your look and your experience with our community.</p><div className="mt-7 flex gap-3"><Button asChild className="rose-gradient rounded-full"><a href="https://www.facebook.com/SnSGlams">Facebook</a></Button><Button asChild variant="outline" className="rounded-full border-rose bg-transparent text-cream"><a href="https://www.instagram.com/sandyfav3">Instagram</a></Button></div></>:null}</Reveal></div></section>}
function Blog(){return <section className="px-5 py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="BEAUTY NOTES" script="From our journal" title="Latest Stories"/><div className="grid gap-7 md:grid-cols-3">{posts.map(p=><Reveal key={p.slug}><Link to="/blog/$slug" params={{slug:p.slug}} className="group block"><div className="aspect-[4/3] overflow-hidden"><img src={p.cover} alt="" loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><p className="mt-4 text-xs uppercase tracking-[.15em] text-rose">{p.category} · {p.readTime}</p><h3 className="mt-2 font-display text-3xl leading-none">{p.title}</h3></Link></Reveal>)}</div></div></section>}
