import { createContext, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { AnimatePresence, motion, useDragControls } from "motion/react";
import { Check, Info, LoaderCircle, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { services, getService, type ServiceId } from "@/data/services";
import { site } from "@/data/site";
import { sendEnquiry } from "@/lib/send-enquiry";

type Selection = { service?: ServiceId; package?: string };
type Pick = { id: ServiceId; pkg: string };
type BookingContextType = { openBooking: (selection?: Selection) => void; closeBooking: () => void };
const BookingContext = createContext<BookingContextType | null>(null);
export const TIME_SLOTS = {
  Morning: ["8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM"],
  Afternoon: ["12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM"],
  Evening: ["5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM"],
  Night: ["8:00 PM", "8:30 PM", "9:00 PM", "9:30 PM", "10:00 PM"],
};
// Same-day requests need at least this much notice before the slot starts.
const LEAD_MINUTES = 60;
const LAST_SLOT = slotMinutes(TIME_SLOTS.Night[TIME_SLOTS.Night.length - 1]!);
const FIELD_LABELS: Record<string, string> = { name: "Full name", email: "Email", phone: "Phone", services: "Service", date: "Preferred date", time: "Preferred time", location: "Location", address: "Venue address", travel: "Relocation fee checkbox", deposit: "Deposit checkbox" };
const fieldLabel = (key: string) => key.startsWith("package-") ? `${getService(key.slice(8))?.name ?? "Service"} package` : FIELD_LABELS[key] ?? key;
/** Minutes after midnight for a slot label like "9:30 AM". */
function slotMinutes(slot: string) { const [, h = "0", m = "0", ap] = /(\d+):(\d+) (AM|PM)/.exec(slot) ?? []; return (Number(h) % 12 + (ap === "PM" ? 12 : 0)) * 60 + Number(m); }
/** Today's date (YYYY-MM-DD) and the current minute of the day at the studio, whatever the visitor's own time zone. */
function studioNow() { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: site.timeZone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date()); const get = (type: string) => parts.find((p) => p.type === type)?.value ?? "00"; return { date: `${get("year")}-${get("month")}-${get("day")}`, minutes: Number(get("hour")) * 60 + Number(get("minute")) }; }
function addDays(date: string, days: number) { const d = new Date(`${date}T12:00:00Z`); d.setUTCDate(d.getUTCDate() + days); return d.toISOString().slice(0, 10); }
const priceLabel = (price: number | null | undefined) => price ? `$${price}` : "Quote on request";
export function useBooking() { const value = useContext(BookingContext); if (!value) throw new Error("useBooking must be used within BookingProvider"); return value; }
export function BookingProvider({ children }: { children: ReactNode }) {
  const [selection, setSelection] = useState<Selection | null>(null);
  const value = useMemo(() => ({ openBooking: (next: Selection = {}) => setSelection(next), closeBooking: () => setSelection(null) }), []);
  return <BookingContext.Provider value={value}>{children}<BookingModal selection={selection} close={value.closeBooking} /></BookingContext.Provider>;
}
function BookingModal({ selection, close }: { selection: Selection | null; close: () => void }) {
  const dialog = useRef<HTMLDivElement>(null); const sheetDrag = useDragControls(); const [picks, setPicks] = useState<Pick[]>([]); const [venue, setVenue] = useState(false); const [date, setDate] = useState(""); const [time, setTime] = useState(""); const [now, setNow] = useState(studioNow); const [status, setStatus] = useState<"idle"|"loading"|"success"|"mailto"|"error">("idle"); const [errors, setErrors] = useState<Record<string,string>>({});
  useEffect(() => { if (!selection) return; setPicks(selection.service ? [{ id: selection.service, pkg: selection.package || "" }] : []); setVenue(false); setDate(""); setTime(""); setNow(studioNow()); setStatus("idle"); setErrors({}); document.body.classList.add("modal-open"); const previous=document.activeElement as HTMLElement|null; setTimeout(()=>dialog.current?.focus(),50); const onKey=(e:KeyboardEvent)=>{ if(e.key==="Escape") close(); }; window.addEventListener("keydown",onKey); const tick=setInterval(()=>setNow(studioNow()),60_000); return()=>{document.body.classList.remove("modal-open");window.removeEventListener("keydown",onKey);clearInterval(tick);previous?.focus();}; }, [selection, close]);
  // Once today's last slot is out of reach, the earliest bookable day is tomorrow.
  const minDate = now.minutes + LEAD_MINUTES > LAST_SLOT ? addDays(now.date, 1) : now.date;
  const isPassed = (slot: string) => date === now.date && slotMinutes(slot) < now.minutes + LEAD_MINUTES;
  const pastDate = Boolean(date) && date < minDate;
  // A chosen time drops out once it becomes unavailable (date changed, or the clock moved on).
  const slot = time && !pastDate && !isPassed(time) ? time : "";
  if (!selection) return null;
  const pickedServices = picks.map((p) => ({ ...p, service: getService(p.id)! })).filter((p) => p.service);
  const lead = pickedServices[0]?.service ?? services[0]!;
  const priced = pickedServices.map((p) => p.service.packages.find((x) => x.name === p.pkg));
  const total = priced.every((p) => p?.price) && priced.length ? priced.reduce((sum, p) => sum + (p?.price ?? 0), 0) : null;
  const summary = pickedServices.length ? pickedServices.map((p) => p.pkg || p.service.name).join(" + ") : "Choose your services";
  function toggleService(id: ServiceId) { setPicks((prev) => prev.some((p) => p.id === id) ? prev.filter((p) => p.id !== id) : [...prev, { id, pkg: "" }]); setErrors(({ services: _s, [`package-${id}`]: _p, ...rest }) => rest); }
  function setPackage(id: ServiceId, pkg: string) { setPicks((prev) => prev.map((p) => p.id === id ? { ...p, pkg } : p)); }
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const formEl=e.currentTarget; const form=new FormData(formEl); const required=["name","email","phone","date","time","location","deposit"]; const next:Record<string,string>={}; required.forEach((key)=>{if(!form.get(key))next[key]="Please complete this field."}); if(!pickedServices.length)next['services']="Choose at least one service."; pickedServices.forEach((p)=>{if(!p.pkg)next[`package-${p.id}`]="Please choose a package."}); if(pastDate)next['date']="That date has passed. Please choose an upcoming date."; if(venue&&!form.get("address"))next['address']="Please add the venue address."; if(venue&&!form.get("travel"))next['travel']="Please acknowledge the relocation fee and travel terms."; const email=String(form.get("email")||""); if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))next['email']="Please enter a valid email address."; setErrors(next); const firstInvalid=Object.keys(next)[0]; if(firstInvalid){ const el=formEl.elements.namedItem(firstInvalid==="services"?`service-${services[0]!.id}`:firstInvalid); if(el instanceof HTMLElement){ el.scrollIntoView({behavior:"smooth",block:"center"}); el.focus({preventScroll:true}); } return; } setStatus("loading"); try { const data=Object.fromEntries([...form.entries()].filter(([key])=>!key.startsWith("package-")&&!key.startsWith("service-"))); const names=pickedServices.map((p)=>p.service.name).join(", "); const packages=pickedServices.map((p,i)=>`${p.service.name}: ${p.pkg} (${priceLabel(priced[i]?.price)})`).join("; "); const result=await sendEnquiry({ subject:`New Booking Request: ${names}`, replyTo:String(data['email']), fields:{ ...data, service:names, package:packages, ...(total?{estimate:`$${total}`}:{}) } }); setStatus(result==="sent"?"success":"mailto"); if(result==="sent")formEl.reset(); } catch (err) { console.error("Booking submission failed:", err); setStatus("error"); } }
  // text-base on mobile keeps iOS Safari from zooming in when a field is focused
  const base="w-full rounded-lg border border-border bg-cream px-3 text-base outline-none focus:ring-2 focus:ring-rose md:text-sm";
  const field=`${base} h-11`;
  const half="col-span-1";
  return <AnimatePresence><motion.div className="fixed inset-0 z-[100] flex items-end justify-center bg-burgundy/80 backdrop-blur-md md:items-center md:p-6" onMouseDown={(e)=>{if(e.target===e.currentTarget)close()}} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div ref={dialog} role="dialog" aria-modal="true" aria-label="Get a quote" tabIndex={-1} drag="y" dragControls={sheetDrag} dragListener={false} dragConstraints={{top:0,bottom:0}} dragElastic={{top:0,bottom:.7}} onDragEnd={(_,info)=>{if(info.offset.y>120||info.velocity.y>600)close()}} initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} exit={{opacity:0,y:40}} className="relative flex max-h-[92dvh] w-full flex-col overflow-hidden rounded-t-3xl bg-cream shadow-2xl outline-none md:max-h-[92vh] md:max-w-6xl md:flex-row md:rounded-2xl">
    <Button aria-label="Close booking" variant="ghost" size="icon" className="absolute right-3 top-5 z-20 md:right-4 md:top-4" onClick={close}><X/></Button>
    <div className="shrink-0 touch-none border-b border-border/70 md:hidden" onPointerDown={(e)=>sheetDrag.start(e)}>
      <div className="flex justify-center pb-2 pt-2.5"><span className="h-1.5 w-11 rounded-full bg-border"/></div>
      <div className="flex items-center gap-3 px-5 pb-3 pr-14"><img src={lead.image} alt="" className="size-12 shrink-0 rounded-xl object-cover"/><div className="min-w-0"><p className="font-display text-2xl uppercase leading-none">Get a Quote</p><p className="mt-1 truncate text-xs text-muted-foreground">{summary}{total ? ` · $${total}` : ""}</p></div></div>
    </div>
    <aside className="relative hidden shrink-0 md:block md:w-[37.5%]"><img src={lead.image} alt={lead.name} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-ink via-burgundy/25 to-transparent"/><div className="absolute inset-x-0 bottom-0 z-10 p-9 text-cream"><p className="font-script text-4xl text-rose">Your moment</p>{pickedServices.length ? <ul className="mt-1 space-y-1.5">{pickedServices.map((p, i) => <li key={p.id}><h2 className={`font-display leading-tight ${pickedServices.length>2?"text-2xl":"text-3xl"}`}>{p.service.name}</h2><p className="text-sm text-cream/85">{p.pkg ? `${p.pkg} · ${priceLabel(priced[i]?.price)}` : "Choose your package"}</p></li>)}</ul> : <h2 className="font-display text-4xl">Choose your services</h2>}{pickedServices.length > 1 && total ? <p className="mt-3 font-display text-xl">Estimated total · ${total}</p> : null}<p className="mt-5 border-t border-rose/50 pt-5 text-sm">A $30 deposit secures your appointment.</p></div></aside>
    <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-5 pt-4 md:p-10">{status==="success"?<div className="flex min-h-[380px] flex-col items-center justify-center pb-8 text-center md:min-h-[520px]"><motion.div initial={{scale:0}} animate={{scale:1}} className="rose-gradient mb-5 grid size-20 place-items-center rounded-full text-cream"><Check className="size-10"/></motion.div><h2 className="font-display text-3xl md:text-4xl">Your request is in!</h2><p className="mt-3 max-w-md text-muted-foreground">We'll email you shortly to confirm your date and deposit.</p><Button className="rose-gradient mt-7 rounded-full text-primary-foreground" onClick={close}>Done</Button></div>:<><div className="hidden md:block"><p className="font-script text-3xl text-rose">Let’s plan your look</p><h2 className="font-display text-4xl uppercase">Get a Quote</h2></div><form onSubmit={submit} className="grid grid-cols-2 gap-x-3 gap-y-3.5 md:mt-6 md:gap-4" noValidate>
      <Field label="Full name" name="name" error={errors['name']}><input name="name" autoComplete="name" maxLength={100} className={field}/></Field><Field label="Email" name="email" error={errors['email']}><input name="email" type="email" inputMode="email" autoComplete="email" maxLength={255} className={field}/></Field><Field className={half} label="Phone" name="phone" error={errors['phone']}><input name="phone" type="tel" inputMode="tel" autoComplete="tel" maxLength={30} className={field}/></Field>
      <Field className={half} label="Occasion" name="occasion"><select name="occasion" className={field}><option>Wedding</option><option>Birthday</option><option>Anniversary</option><option>Graduation</option><option>Photoshoot</option><option>Other</option></select></Field>
      <fieldset className="col-span-2"><legend className="mb-1 block text-xs font-medium md:text-sm">Services * <span className="font-normal text-muted-foreground">(choose one or more)</span></legend><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{services.map((s)=>{const on=picks.some((p)=>p.id===s.id);return <button key={s.id} type="button" name={`service-${s.id}`} aria-pressed={on} onClick={()=>toggleService(s.id)} className={`flex h-11 items-center justify-center gap-1.5 rounded-lg border px-2 text-sm transition focus:outline-none focus-visible:ring-2 focus-visible:ring-rose ${on?"border-rose bg-rose text-cream":"border-border bg-cream hover:border-rose/60"}`}>{on&&<Check className="size-4 shrink-0"/>}<span className="truncate">{s.name}</span></button>})}</div>{errors['services']&&<span className="mt-1 block text-xs text-destructive">{errors['services']}</span>}</fieldset>
      {pickedServices.map((p)=><Field key={p.id} label={`${p.service.name} package`} name={`package-${p.id}`} required error={errors[`package-${p.id}`]}><select name={`package-${p.id}`} value={p.pkg} onChange={(e)=>setPackage(p.id,e.target.value)} className={field}><option value="">Select a package</option>{p.service.packages.map(x=><option key={x.name} value={x.name}>{x.name}{x.price?` — $${x.price}`:" — Quote on request"}</option>)}</select></Field>)}
      <Field className={half} label="Number of people" name="people"><select name="people" className={field}>{["1","2","3","4","5","6","7","8","9","10+"].map(x=><option key={x}>{x}</option>)}</select></Field>
      <Field className={half} label="Location" name="location" error={errors['location']}><select name="location" className={field} onChange={(e)=>setVenue(e.target.value==="At my venue")}><option value="At the studio">At the studio</option><option value="At my venue">At my venue (relocation fee)</option></select></Field>
      {venue&&<><div className="col-span-2 flex gap-2.5 rounded-lg border border-rose/40 bg-blush p-3 text-xs leading-relaxed md:text-sm"><Info className="mt-0.5 size-4 shrink-0 text-rose"/><p><strong className="font-medium">Venue bookings:</strong> {site.travelPolicy.summary}</p></div><Field className="col-span-2" label="Venue address" name="address" error={errors['address']}><input name="address" autoComplete="street-address" maxLength={250} className={field}/></Field><label className="col-span-2 flex items-start gap-3 text-xs leading-relaxed md:text-sm"><input type="checkbox" name="travel" className="mt-0.5 size-4 shrink-0 accent-rose"/><span>I understand a relocation fee applies, my venue must be within {site.travelPolicy.radiusMiles} miles of the SnS Glams studio, and venue bookings are subject to cancellation.</span></label>{errors['travel']&&<p className="col-span-2 -mt-2 text-xs text-destructive">{errors['travel']}</p>}</>}
      <Field className={half} label="Preferred date" name="date" error={errors['date']}><input name="date" type="date" min={minDate} value={date} onChange={(e)=>setDate(e.target.value)} className={field}/></Field>
      <Field className={half} label="Preferred time" name="time" error={errors['time']}><select name="time" value={slot} onChange={(e)=>setTime(e.target.value)} className={`${field} ${slot?"":"text-muted-foreground"}`}><option value="">{date?"Choose a time":"Pick a date first"}</option>{Object.entries(TIME_SLOTS).map(([group,slots])=><optgroup key={group} label={group}>{slots.map(slot=>{const off=!date||pastDate||isPassed(slot);return <option key={slot} value={slot} disabled={off} className={off?"text-muted-foreground":"text-foreground"}>{slot}{date&&!pastDate&&isPassed(slot)?" — unavailable":""}</option>})}</optgroup>)}</select></Field>
      {date===now.date&&<p className="col-span-2 -mt-1.5 text-xs text-muted-foreground">Times that have passed (or start within the next hour) are greyed out.</p>}
      <label className="col-span-2"><span className="mb-1 block text-xs font-medium md:text-sm">Notes</span><textarea name="notes" maxLength={1000} rows={3} className={`${base} h-20 py-2.5 md:h-auto`} placeholder="Inspiration, hair details, or anything we should know"/></label>
      <input name="botcheck" className="hidden" tabIndex={-1} autoComplete="off"/>
      <label className="col-span-2 flex items-start gap-3 text-xs leading-relaxed md:text-sm"><input type="checkbox" name="deposit" className="mt-0.5 size-4 shrink-0 accent-rose"/><span>I understand a $30 deposit secures my booking. SnS Glams will email me to confirm and send deposit details.</span></label>{errors['deposit']&&<p className="col-span-2 -mt-2 text-xs text-destructive">{errors['deposit']}</p>}
      {Object.keys(errors).length>0&&<p role="alert" className="col-span-2 rounded-lg bg-blush p-3 text-sm text-destructive">Please complete the highlighted fields above: {Object.keys(errors).map(fieldLabel).join(", ")}.</p>}
      {status==="mailto"&&<p className="col-span-2 rounded-lg bg-blush p-3 text-sm">We opened your email app with your booking details. Just press send, or email us at <a className="underline" href={`mailto:${site.email}`}>{site.email}</a>.</p>}
      {status==="error"&&<p className="col-span-2 rounded-lg bg-blush p-3 text-sm">We couldn't send your request. Please <a className="underline" href={`mailto:${site.email}`}>email us directly</a>.</p>}
      {/* On mobile the submit button stays pinned to the bottom of the sheet while the form scrolls */}
      <div className="sticky bottom-0 z-10 col-span-2 -mx-5 border-t border-border/70 bg-cream/95 px-5 pb-[max(.75rem,env(safe-area-inset-bottom))] pt-3 backdrop-blur md:static md:mx-0 md:border-0 md:bg-transparent md:p-0 md:backdrop-blur-none"><Button disabled={status==="loading"} className="rose-gradient h-12 w-full rounded-full text-primary-foreground">{status==="loading"?<><LoaderCircle className="animate-spin"/> Sending…</>:"Send Booking Request"}</Button></div>
    </form></>}</div>
  </motion.div></motion.div></AnimatePresence>;
}
function Field({label,name,error,required,className="col-span-2 md:col-span-1",children}:{label:string;name:string;error?:string|undefined;required?:boolean;className?:string;children:ReactNode}) { return <label className={className}><span className="mb-1 block text-xs font-medium md:text-sm">{label}{required||["name","email","phone","date","time","location"].includes(name)?" *":""}</span>{children}{error&&<span className="mt-1 block text-xs text-destructive">{error}</span>}</label> }
