import { createContext, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { AnimatePresence, motion, useDragControls } from "motion/react";
import { Check, LoaderCircle, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { services, getService, type ServiceId } from "@/data/services";
import { site } from "@/data/site";
import { sendEnquiry } from "@/lib/send-enquiry";

type Selection = { service?: ServiceId; package?: string };
type BookingContextType = { openBooking: (selection?: Selection) => void; closeBooking: () => void };
const BookingContext = createContext<BookingContextType | null>(null);
export const TIME_SLOTS = {
  Morning: ["8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM"],
  Afternoon: ["12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM"],
  Evening: ["5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM"],
  Night: ["8:00 PM", "8:30 PM", "9:00 PM", "9:30 PM", "10:00 PM"],
};
const FIELD_LABELS: Record<string, string> = { name: "Full name", email: "Email", phone: "Phone", package: "Package", date: "Preferred date", time: "Preferred time", location: "Location", address: "Venue address", deposit: "Deposit checkbox" };
export function useBooking() { const value = useContext(BookingContext); if (!value) throw new Error("useBooking must be used within BookingProvider"); return value; }
export function BookingProvider({ children }: { children: ReactNode }) {
  const [selection, setSelection] = useState<Selection | null>(null);
  const value = useMemo(() => ({ openBooking: (next: Selection = {}) => setSelection(next), closeBooking: () => setSelection(null) }), []);
  return <BookingContext.Provider value={value}>{children}<BookingModal selection={selection} close={value.closeBooking} /></BookingContext.Provider>;
}
function BookingModal({ selection, close }: { selection: Selection | null; close: () => void }) {
  const dialog = useRef<HTMLDivElement>(null); const sheetDrag = useDragControls(); const [serviceId, setServiceId] = useState<ServiceId>(selection?.service || "makeup"); const [packageName, setPackageName] = useState(selection?.package || ""); const [venue, setVenue] = useState(false); const [status, setStatus] = useState<"idle"|"loading"|"success"|"mailto"|"error">("idle"); const [errors, setErrors] = useState<Record<string,string>>({});
  const service = getService(serviceId);
  useEffect(() => { if (!selection) return; setServiceId(selection.service || "makeup"); setPackageName(selection.package || ""); setStatus("idle"); setErrors({}); document.body.classList.add("modal-open"); const previous=document.activeElement as HTMLElement|null; setTimeout(()=>dialog.current?.focus(),50); const onKey=(e:KeyboardEvent)=>{ if(e.key==="Escape") close(); }; window.addEventListener("keydown",onKey); return()=>{document.body.classList.remove("modal-open");window.removeEventListener("keydown",onKey);previous?.focus();}; }, [selection, close]);
  if (!selection || !service) return null;
  const currentService = service;
  const selectedPackage = service.packages.find((p)=>p.name===packageName);
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const formEl=e.currentTarget; const form=new FormData(formEl); const required=["name","email","phone","package","date","time","location","deposit"]; const next:Record<string,string>={}; required.forEach((key)=>{if(!form.get(key))next[key]="Please complete this field."}); if(venue&&!form.get("address"))next['address']="Please add the venue address."; const email=String(form.get("email")||""); if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))next['email']="Please enter a valid email address."; setErrors(next); const firstInvalid=Object.keys(next)[0]; if(firstInvalid){ const el=formEl.elements.namedItem(firstInvalid); if(el instanceof HTMLElement){ el.scrollIntoView({behavior:"smooth",block:"center"}); el.focus({preventScroll:true}); } return; } setStatus("loading"); try { const data=Object.fromEntries(form.entries()); const result=await sendEnquiry({ subject:`New Booking Request: ${currentService.name} (${packageName})`, replyTo:String(data['email']), fields:{ ...data, service:currentService.name } }); setStatus(result==="sent"?"success":"mailto"); if(result==="sent")formEl.reset(); } catch (err) { console.error("Booking submission failed:", err); setStatus("error"); } }
  // text-base on mobile keeps iOS Safari from zooming in when a field is focused
  const base="w-full rounded-lg border border-border bg-cream px-3 text-base outline-none focus:ring-2 focus:ring-rose md:text-sm";
  const field=`${base} h-11`;
  const half="col-span-1";
  return <AnimatePresence><motion.div className="fixed inset-0 z-[100] flex items-end justify-center bg-burgundy/80 backdrop-blur-md md:items-center md:p-6" onMouseDown={(e)=>{if(e.target===e.currentTarget)close()}} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div ref={dialog} role="dialog" aria-modal="true" aria-label="Get a quote" tabIndex={-1} drag="y" dragControls={sheetDrag} dragListener={false} dragConstraints={{top:0,bottom:0}} dragElastic={{top:0,bottom:.7}} onDragEnd={(_,info)=>{if(info.offset.y>120||info.velocity.y>600)close()}} initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} exit={{opacity:0,y:40}} className="relative flex max-h-[92dvh] w-full flex-col overflow-hidden rounded-t-3xl bg-cream shadow-2xl outline-none md:grid md:h-auto md:max-h-[92vh] md:max-w-6xl md:grid-cols-[.75fr_1.25fr] md:rounded-2xl">
    <Button aria-label="Close booking" variant="ghost" size="icon" className="absolute right-3 top-5 z-20 md:right-4 md:top-4" onClick={close}><X/></Button>
    <div className="shrink-0 touch-none border-b border-border/70 md:hidden" onPointerDown={(e)=>sheetDrag.start(e)}>
      <div className="flex justify-center pb-2 pt-2.5"><span className="h-1.5 w-11 rounded-full bg-border"/></div>
      <div className="flex items-center gap-3 px-5 pb-3 pr-14"><img src={service.image} alt="" className="size-12 shrink-0 rounded-xl object-cover"/><div className="min-w-0"><p className="font-display text-2xl uppercase leading-none">Get a Quote</p><p className="mt-1 truncate text-xs text-muted-foreground">{service.name} · {packageName || "Choose your package"}{selectedPackage?.price ? ` · $${selectedPackage.price}` : ""}</p></div></div>
    </div>
    <aside className="relative hidden min-h-[680px] md:block"><img src={service.image} alt={service.name} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-ink via-burgundy/25 to-transparent"/><div className="absolute inset-x-0 bottom-0 z-10 p-9 text-cream"><p className="font-script text-4xl text-rose">Your moment</p><h2 className="font-display text-4xl">{service.name}</h2><p>{packageName || "Choose your package"} {selectedPackage ? `· $${selectedPackage.price}` : ""}</p><p className="mt-5 border-t border-rose/50 pt-5 text-sm">A $30 deposit secures your appointment.</p></div></aside>
    <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-5 pt-4 md:p-10">{status==="success"?<div className="flex min-h-[380px] flex-col items-center justify-center pb-8 text-center md:min-h-[520px]"><motion.div initial={{scale:0}} animate={{scale:1}} className="rose-gradient mb-5 grid size-20 place-items-center rounded-full text-cream"><Check className="size-10"/></motion.div><h2 className="font-display text-3xl md:text-4xl">Your request is in!</h2><p className="mt-3 max-w-md text-muted-foreground">We'll email you shortly to confirm your date and deposit.</p><Button className="rose-gradient mt-7 rounded-full text-primary-foreground" onClick={close}>Done</Button></div>:<><div className="hidden md:block"><p className="font-script text-3xl text-rose">Let’s plan your look</p><h2 className="font-display text-4xl uppercase">Get a Quote</h2></div><form onSubmit={submit} className="grid grid-cols-2 gap-x-3 gap-y-3.5 md:mt-6 md:gap-4" noValidate>
      <Field label="Full name" name="name" error={errors['name']}><input name="name" autoComplete="name" maxLength={100} className={field}/></Field><Field label="Email" name="email" error={errors['email']}><input name="email" type="email" inputMode="email" autoComplete="email" maxLength={255} className={field}/></Field><Field className={half} label="Phone" name="phone" error={errors['phone']}><input name="phone" type="tel" inputMode="tel" autoComplete="tel" maxLength={30} className={field}/></Field>
      <Field className={half} label="Service" name="service"><select name="service" value={serviceId} onChange={(e)=>{setServiceId(e.target.value as ServiceId);setPackageName("")}} className={field}>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>
      <Field label="Package" name="package" error={errors['package']}><select name="package" value={packageName} onChange={(e)=>setPackageName(e.target.value)} className={field}><option value="">Select a package</option>{service.packages.map(p=><option key={p.name} value={p.name}>{p.name}{p.price?` — $${p.price}`:" — Quote on request"}</option>)}</select></Field>
      <Field className={half} label="Occasion" name="occasion"><select name="occasion" className={field}><option>Wedding</option><option>Birthday</option><option>Anniversary</option><option>Graduation</option><option>Photoshoot</option><option>Other</option></select></Field>
      <Field className={half} label="Number of people" name="people"><select name="people" className={field}>{["1","2","3","4","5","6","7","8","9","10+"].map(x=><option key={x}>{x}</option>)}</select></Field>
      <Field className={half} label="Preferred date" name="date" error={errors['date']}><input name="date" type="date" min={new Date().toISOString().split("T")[0]} className={field}/></Field>
      <Field className={half} label="Preferred time" name="time" error={errors['time']}><select name="time" className={field}><option value="">Choose a time</option>{Object.entries(TIME_SLOTS).map(([group,slots])=><optgroup key={group} label={group}>{slots.map(slot=><option key={slot}>{slot}</option>)}</optgroup>)}</select></Field>
      <Field label="Location" name="location" error={errors['location']}><select name="location" className={field} onChange={(e)=>setVenue(e.target.value==="At my venue")}><option>At the studio</option><option>At my venue</option></select></Field>
      {venue&&<Field className="col-span-2" label="Venue address" name="address" error={errors['address']}><input name="address" autoComplete="street-address" maxLength={250} className={field}/></Field>}
      <label className="col-span-2"><span className="mb-1 block text-xs font-medium md:text-sm">Notes</span><textarea name="notes" maxLength={1000} rows={3} className={`${base} h-20 py-2.5 md:h-auto`} placeholder="Inspiration, hair details, or anything we should know"/></label>
      <input name="botcheck" className="hidden" tabIndex={-1} autoComplete="off"/>
      <label className="col-span-2 flex items-start gap-3 text-xs leading-relaxed md:text-sm"><input type="checkbox" name="deposit" className="mt-0.5 size-4 shrink-0 accent-rose"/><span>I understand a $30 deposit secures my booking. SnS Glams will email me to confirm and send deposit details.</span></label>{errors['deposit']&&<p className="col-span-2 -mt-2 text-xs text-destructive">{errors['deposit']}</p>}
      {Object.keys(errors).length>0&&<p role="alert" className="col-span-2 rounded-lg bg-blush p-3 text-sm text-destructive">Please complete the highlighted fields above: {Object.keys(errors).map((k)=>FIELD_LABELS[k]??k).join(", ")}.</p>}
      {status==="mailto"&&<p className="col-span-2 rounded-lg bg-blush p-3 text-sm">We opened your email app with your booking details. Just press send, or email us at <a className="underline" href={`mailto:${site.email}`}>{site.email}</a>.</p>}
      {status==="error"&&<p className="col-span-2 rounded-lg bg-blush p-3 text-sm">We couldn't send your request. Please <a className="underline" href={`mailto:${site.email}`}>email us directly</a>.</p>}
      {/* On mobile the submit button stays pinned to the bottom of the sheet while the form scrolls */}
      <div className="sticky bottom-0 z-10 col-span-2 -mx-5 border-t border-border/70 bg-cream/95 px-5 pb-[max(.75rem,env(safe-area-inset-bottom))] pt-3 backdrop-blur md:static md:mx-0 md:border-0 md:bg-transparent md:p-0 md:backdrop-blur-none"><Button disabled={status==="loading"} className="rose-gradient h-12 w-full rounded-full text-primary-foreground">{status==="loading"?<><LoaderCircle className="animate-spin"/> Sending…</>:"Send Booking Request"}</Button></div>
    </form></>}</div>
  </motion.div></motion.div></AnimatePresence>;
}
function Field({label,name,error,className="col-span-2 md:col-span-1",children}:{label:string;name:string;error?:string|undefined;className?:string;children:ReactNode}) { return <label className={className}><span className="mb-1 block text-xs font-medium md:text-sm">{label}{["name","email","phone","package","date","time","location"].includes(name)?" *":""}</span>{children}{error&&<span className="mt-1 block text-xs text-destructive">{error}</span>}</label> }
