import { motion } from "motion/react";
import { Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useBooking } from "./booking";
import type { ServiceId } from "@/data/services";
import { media } from "@/data/media";
import { site } from "@/data/site";
export function Reveal({children,className=""}:{children:React.ReactNode;className?:string}){return <motion.div className={className} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-60px"}} transition={{duration:.7}}>{children}</motion.div>}
export function SectionHeading({eyebrow,script,title,light=false}:{eyebrow?:string;script?:string;title:string;light?:boolean}){return <Reveal><div className={`mb-10 ${light?"text-cream":"text-burgundy"}`}>{eyebrow&&<p className="mb-2 text-xs tracking-[.24em]">{eyebrow}</p>}{script&&<p className="font-script text-4xl text-rose">{script}</p>}<h2 className="max-w-3xl font-display text-4xl uppercase leading-[.95] sm:text-6xl">{title}</h2></div></Reveal>}
export function BookButton({service,packageName,label="Book Now",className=""}:{service?:ServiceId;packageName?:string;label?:React.ReactNode;className?:string}){const {openBooking}=useBooking();return <Button onClick={()=>openBooking({...service ? {service} : {}, ...packageName ? {package: packageName} : {}})} className={`rose-gradient rounded-full px-7 text-primary-foreground ${className}`}>{label}</Button>}
export function CTABanner(){const {openBooking}=useBooking();return <section className="relative overflow-hidden bg-wine text-cream"><img src={media.roses} alt="" aria-hidden loading="lazy" className="absolute inset-0 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-gradient-to-r from-wine/90 via-wine/60 to-wine/90"/><Curve className="absolute inset-x-0 -top-px rotate-180 text-background"/><Reveal className="relative z-10 mx-auto flex max-w-3xl flex-col items-center px-5 pb-20 pt-24 text-center"><p className="font-script text-4xl text-petal sm:text-5xl">Your moment awaits</p><h2 className="mt-1 font-display text-4xl uppercase tracking-[.06em] sm:text-5xl">Ready for Your Glow-Up?</h2><div className="mt-8 flex flex-wrap justify-center gap-3"><Button onClick={()=>openBooking()} className="rose-gradient h-11 rounded-full px-8 text-xs uppercase tracking-[.18em] text-primary-foreground">Book Now <ArrowRight/></Button><Button asChild variant="outline" className="h-11 rounded-full border-cream/60 bg-transparent px-8 text-xs uppercase tracking-[.18em] text-cream hover:bg-cream hover:text-burgundy"><a href={`mailto:${site.email}`}>Email Us <ArrowRight/></a></Button></div></Reveal></section>}
/** Soft wave divider; set its colour with a text-* class matching the section it flows into. */
export function Curve({className=""}:{className?:string}){return <svg aria-hidden viewBox="0 0 1440 64" preserveAspectRatio="none" className={`pointer-events-none block h-8 w-full sm:h-12 lg:h-16 ${className}`}><path d="M0 34C240 6 480 0 720 18s480 44 720 20v26H0Z" fill="currentColor"/></svg>}
export function PageHero({script,title,description,image}:{script:string;title:string;description?:string;image?:string}){return <section className="relative flex min-h-[68vh] items-end overflow-hidden bg-burgundy px-5 pb-16 pt-32 text-cream sm:pb-24">{image&&<img src={image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-45"/>}<div className="absolute inset-0 bg-gradient-to-r from-ink via-burgundy/70 to-transparent"/><div className="relative z-10 mx-auto w-full max-w-7xl"><p className="font-script text-4xl text-rose sm:text-5xl">{script}</p><h1 className="max-w-4xl font-display text-5xl uppercase leading-[.9] sm:text-8xl">{title}</h1>{description&&<p className="mt-5 max-w-xl text-cream/80">{description}</p>}</div></section>}
export function TextLink({to,children}:{to:string;children:React.ReactNode}){return <Button asChild variant="outline" className="rounded-full border-rose bg-transparent text-burgundy"><Link to={to}>{children}<ArrowRight/></Link></Button>}
