import { useEffect, useState } from "react";
import { Link, useRouterState } from "@tanstack/react-router";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import Lenis from "lenis";
import { ChevronDown, Instagram, Facebook, Menu, X, Youtube } from "lucide-react";
import { Button } from "@/components/ui/button";
import { BookingProvider, useBooking } from "./booking";
import { services } from "@/data/services";
import { site } from "@/data/site";

export function AppShell({ children }: { children: React.ReactNode }) {
 const pathname=useRouterState({select:s=>s.location.pathname}); const reduce=useReducedMotion();
 useEffect(()=>{if(reduce)return;const lenis=new Lenis({duration:1.15,smoothWheel:true});let id=0;const raf=(t:number)=>{lenis.raf(t);id=requestAnimationFrame(raf)};id=requestAnimationFrame(raf);return()=>{cancelAnimationFrame(id);lenis.destroy()}},[reduce]);
 useEffect(()=>window.scrollTo(0,0),[pathname]);
 return <BookingProvider><Header/><AnimatePresence mode="wait"><motion.main key={pathname} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.35}}>{children}</motion.main></AnimatePresence><Footer/></BookingProvider>
}
function Header(){const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);const path=useRouterState({select:s=>s.location.pathname});const {openBooking}=useBooking();useEffect(()=>{const fn=()=>setScrolled(scrollY>30);fn();addEventListener("scroll",fn,{passive:true});return()=>removeEventListener("scroll",fn)},[]);useEffect(()=>setOpen(false),[path]);const overlay=path==="/"&&!scrolled;
 return <header className={`fixed inset-x-0 top-0 z-50 transition-all ${overlay?"bg-transparent text-cream":"bg-cream/95 text-burgundy shadow-sm backdrop-blur-lg"}`}><div className="mx-auto flex h-20 max-w-[1500px] items-center justify-between px-5 lg:px-10"><Brand/><nav className="hidden items-center gap-7 text-xs uppercase md:flex"><NavLink to="/">Home</NavLink><NavLink to="/about">About</NavLink><div className="group relative"><Link to="/services" className="flex items-center gap-1 py-8">Services <ChevronDown className="size-3"/></Link><div className="invisible absolute left-1/2 w-60 -translate-x-1/2 border border-border bg-cream p-2 text-burgundy opacity-0 shadow-xl transition group-hover:visible group-hover:opacity-100">{services.map(s=><Link key={s.id} to={s.href} className="block px-4 py-3 hover:bg-blush">{s.name}</Link>)}</div></div><NavLink to="/gallery">Gallery</NavLink><NavLink to="/reviews">Reviews</NavLink><NavLink to="/blog">Blog</NavLink><NavLink to="/contact">Contact</NavLink></nav><div className="flex items-center gap-2"><Button onClick={()=>openBooking()} className="rose-gradient hidden rounded-full px-6 text-primary-foreground sm:inline-flex">Book Now</Button><Button variant="ghost" size="icon" className="md:hidden" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu/></Button></div></div>
 <AnimatePresence>{open&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 flex flex-col bg-burgundy p-6 text-cream grain"><div className="flex justify-between"><Brand/><Button variant="ghost" size="icon" onClick={()=>setOpen(false)} aria-label="Close menu"><X/></Button></div><nav className="z-10 my-auto flex flex-col gap-4 font-display text-4xl">{[["/","Home"],["/about","About"],["/services","Services"],["/gallery","Gallery"],["/reviews","Reviews"],["/blog","Blog"],["/contact","Contact"]].map(([to,label],i)=><motion.div key={to} initial={{x:-20,opacity:0}} animate={{x:0,opacity:1}} transition={{delay:i*.05}}><Link to={to}>{label}</Link></motion.div>)}</nav><Button onClick={()=>openBooking()} className="rose-gradient z-10 rounded-full text-primary-foreground">Book Now</Button></motion.div>}</AnimatePresence></header>}
function NavLink({to,children}:{to:string;children:React.ReactNode}){return <Link to={to} activeProps={{className:"text-rose"}} className="py-8 transition hover:text-rose">{children}</Link>}
export function Brand(){return <Link to="/" className="relative z-10 text-center leading-none"><span className="block font-display text-2xl">SnS Glams</span><span className="block text-[8px] tracking-[.28em]">HAIR &amp; MAKEUP STUDIO</span></Link>}
function Footer(){const year=new Date().getFullYear();return <footer className="grain bg-ink px-5 py-16 text-cream"><div className="relative z-10 mx-auto grid max-w-7xl gap-10 md:grid-cols-4"><div><Brand/><p className="mt-5 text-sm text-cream/70">Beauty, artistry and confidence—all under one roof.</p><div className="mt-5 flex gap-4"><a aria-label="Instagram" href={site.socials.instagram}><Instagram/></a><a aria-label="Facebook" href={site.socials.facebook}><Facebook/></a><a aria-label="YouTube" href={site.socials.youtube}><Youtube/></a></div></div><FooterCol title="Quick Links" links={[["/about","Our Story"],["/gallery","Gallery"],["/reviews","Reviews"],["/blog","Journal"]]}/><FooterCol title="Services" links={services.map(s=>[s.href,s.name])}/><div><h3 className="font-display text-xl">Visit the Studio</h3><p className="mt-4 text-sm text-cream/70">{site.address}</p><a className="mt-2 block text-sm text-cream/70" href={`mailto:${site.email}`}>{site.email}</a><p className="mt-2 text-sm text-cream/70">Open 7 days</p></div></div><div className="relative z-10 mx-auto mt-12 flex max-w-7xl flex-col justify-between gap-4 border-t border-cream/15 pt-6 text-xs text-cream/55 md:flex-row"><span>© {year} SnS Glams Hair &amp; Makeup Studio</span><div className="flex gap-5"><Link to="/privacy-policy">Privacy Policy</Link><Link to="/disclaimer">Disclaimer</Link><Link to="/faq">FAQ's</Link></div></div></footer>}
function FooterCol({title,links}:{title:string;links:string[][]}){return <div><h3 className="font-display text-xl">{title}</h3><div className="mt-4 space-y-2 text-sm text-cream/70">{links.map(([to,label])=><Link key={to} to={to} className="block hover:text-rose">{label}</Link>)}</div></div>}
